<?php
/**
 * Plugin Name: WBB — Business Manager Role
 * Description: Adds a "Business Manager" role limited to Bookings, Pages,
 *              Gift Vouchers, Site Settings and Reviews — and nothing else.
 *              Loaded as a must-use plugin so the capability wiring is always
 *              present (the custom plugins/theme gate on the wbb_manage cap it
 *              defines).
 *
 * WHY A CUSTOM CAPABILITY?
 * The Bookings + Gift Vouchers plugins and the theme's Site Settings page used
 * to require `manage_options` (full administrator). Those gates now require the
 * custom `wbb_manage` capability instead, which is granted to both the
 * administrator and business_manager roles below. Reviews (the wbb_review CPT)
 * use their own capability set so they don't drag in the core Posts editor.
 *
 * To change what the role can do, edit the cap lists and bump WBB_BM_VERSION.
 */

defined( 'ABSPATH' ) || exit;

const WBB_BM_ROLE    = 'business_manager';
const WBB_BM_VERSION = 1; // Bump to force a capability re-sync.

/**
 * Capabilities granted to the Business Manager role.
 *
 * @return array<string,bool>
 */
function wbb_bm_role_caps() {
	$caps = array(
		// Baseline: log in to wp-admin + manage media for pages/reviews.
		'read'        => true,
		'upload_files' => true,

		// Custom gate for Bookings, Gift Vouchers and Site Settings.
		'wbb_manage'  => true,
	);

	// Pages — full management.
	foreach ( array(
		'edit_pages', 'edit_others_pages', 'edit_published_pages', 'edit_private_pages',
		'publish_pages',
		'delete_pages', 'delete_others_pages', 'delete_published_pages', 'delete_private_pages',
		'read_private_pages',
	) as $cap ) {
		$caps[ $cap ] = true;
	}

	// Reviews (wbb_review CPT) — full management. Mirrors the caps generated by
	// capability_type [ 'wbb_review', 'wbb_reviews' ] in cpt-reviews.php.
	foreach ( wbb_bm_review_caps() as $cap ) {
		$caps[ $cap ] = true;
	}

	return $caps;
}

/**
 * The custom Reviews capabilities (also granted to administrators).
 *
 * @return string[]
 */
function wbb_bm_review_caps() {
	return array(
		'edit_wbb_reviews', 'edit_others_wbb_reviews', 'edit_published_wbb_reviews', 'edit_private_wbb_reviews',
		'publish_wbb_reviews',
		'delete_wbb_reviews', 'delete_others_wbb_reviews', 'delete_published_wbb_reviews', 'delete_private_wbb_reviews',
		'read_private_wbb_reviews',
	);
}

/**
 * Create/refresh the role and make sure administrators keep access to the
 * custom-capability areas. Runs only when the stored version is behind.
 */
function wbb_bm_sync_roles() {
	if ( (int) get_option( 'wbb_bm_version' ) === WBB_BM_VERSION ) {
		return;
	}

	// Re-create the role cleanly. Removing then re-adding the same slug keeps
	// any already-assigned users (their membership lives in user meta).
	remove_role( WBB_BM_ROLE );
	add_role( WBB_BM_ROLE, __( 'Business Manager', 'wbb' ), wbb_bm_role_caps() );

	// Administrators gate on the same custom caps now, so grant them too.
	$admin = get_role( 'administrator' );
	if ( $admin ) {
		$admin->add_cap( 'wbb_manage' );
		foreach ( wbb_bm_review_caps() as $cap ) {
			$admin->add_cap( $cap );
		}
	}

	update_option( 'wbb_bm_version', WBB_BM_VERSION );
}
// Run early (before the current-user object is built for the request) so newly
// granted administrator caps take effect on the very first load after deploy.
add_action( 'plugins_loaded', 'wbb_bm_sync_roles' );

/**
 * True for a Business Manager (has the custom cap but isn't a full admin).
 * Used to scope the Dashboard tweaks below without affecting administrators.
 */
function wbb_bm_is_manager() {
	return current_user_can( 'wbb_manage' ) && ! current_user_can( 'manage_options' );
}

// The Business Manager has no use for the Dashboard — remove the menu item.
add_action( 'admin_menu', function () {
	if ( wbb_bm_is_manager() ) {
		remove_menu_page( 'index.php' );
	}
}, 999 );

// …and send them straight to Bookings if they land on the Dashboard (e.g. the
// default post-login destination of wp-admin/).
add_action( 'admin_init', function () {
	if ( ! wbb_bm_is_manager() || wp_doing_ajax() ) {
		return;
	}
	if ( 'index.php' === $GLOBALS['pagenow'] ) {
		wp_safe_redirect( admin_url( 'admin.php?page=wbb-bookings' ) );
		exit;
	}
} );
